export {default as Header} from "./Header/Header"
export {default as Footer} from "./Footer/Footer"
export {default as TextForm} from "./TextForm/TextForm"
export {default as About} from "./About/About"
export {default as Alert} from "./Alert/Alert"